import fs from "node:fs";
import path from "node:path";

const ROLES = new Set(["code-ui", "graphic-primitive", "background-plate", "cutout-subject", "inline-photo", "generated-clean"]);
const RENDERERS = new Set(["code", "image2", "project"]);
const PLACEMENTS = new Set(["code", "background", "layered", "container"]);
const OVERLAYS = new Set(["none", "side-by-side", "safe-overlap", "masked-overlay", "cutout-layered", "card-overlay"]);
const MASKS = new Set(["none", "gradient", "solid-backplate", "blur"]);
const CODE_ROLES = new Set(["code-ui", "graphic-primitive"]);
const RASTER_ROLES = new Set(["background-plate", "cutout-subject", "inline-photo", "generated-clean"]);

export function runVisualRoleGuard({ rootDir, workflowMode = null } = {}) {
  if (!rootDir) return [];
  const planFile = findVisualRolePlan(rootDir);
  if (!planFile) {
    const assetPlan = findNamedPlan(rootDir, "asset-plan.json");
    if (assetPlan && ["recreate", "redesign", "create"].includes(workflowMode)) {
      return [{
        level: "warn",
        rule: "visual-role-plan-missing",
        message: "An asset plan exists but visual-role-plan.json is missing. New UI runs should classify assetRole + overlayRole before implementation so image/text overlap decisions are explicit.",
        file: assetPlan,
      }];
    }
    return [];
  }

  let plan;
  try {
    plan = JSON.parse(fs.readFileSync(planFile, "utf8"));
  } catch (error) {
    return [fail("visual-role-plan-invalid-json", `Could not parse ${path.relative(rootDir, planFile)}: ${error.message}`, planFile)];
  }

  const findings = [];
  if (!plan || typeof plan !== "object" || Array.isArray(plan)) {
    return [fail("visual-role-plan-invalid", "visual-role-plan.json must be a JSON object.", planFile)];
  }
  if (plan.version !== 1) findings.push(fail("visual-role-plan-version", "visual-role-plan.json must use version 1.", planFile));
  if (!Array.isArray(plan.elements) || plan.elements.length === 0) {
    findings.push(fail("visual-role-plan-elements", "visual-role-plan.json requires a non-empty elements array.", planFile));
    return findings;
  }

  const seen = new Set();
  for (const element of plan.elements) validateElement(element, planFile, findings, seen);
  return findings;
}

function validateElement(element, planFile, findings, seen) {
  if (!element || typeof element !== "object" || Array.isArray(element)) {
    findings.push(fail("visual-role-entry-invalid", "Each visual-role element must be an object.", planFile));
    return;
  }
  const id = nonEmpty(element.id) ? element.id : "<missing-id>";
  if (!nonEmpty(element.id)) findings.push(fail("visual-role-id", "Each visual-role element requires a stable id.", planFile));
  if (seen.has(id)) findings.push(fail("visual-role-id-duplicate", `Duplicate visual-role id ${id}.`, planFile));
  seen.add(id);

  const asset = element.assetRole;
  const overlay = element.overlayRole;
  if (!asset || typeof asset !== "object") {
    findings.push(fail("asset-role-missing", `Element ${id} requires assetRole.`, planFile));
    return;
  }
  if (!overlay || typeof overlay !== "object") {
    findings.push(fail("overlay-role-missing", `Element ${id} requires overlayRole.`, planFile));
    return;
  }

  const role = asset.role;
  const renderer = asset.renderer;
  const placement = asset.placement;
  const mode = overlay.mode;

  if (!ROLES.has(role)) findings.push(fail("asset-role-invalid", `Element ${id} has unsupported assetRole.role ${JSON.stringify(role)}.`, planFile));
  if (!RENDERERS.has(renderer)) findings.push(fail("asset-renderer-invalid", `Element ${id} has unsupported renderer ${JSON.stringify(renderer)}.`, planFile));
  if (!PLACEMENTS.has(placement)) findings.push(fail("asset-placement-invalid", `Element ${id} has unsupported placement ${JSON.stringify(placement)}.`, planFile));
  if (!OVERLAYS.has(mode)) findings.push(fail("overlay-role-invalid", `Element ${id} has unsupported overlay mode ${JSON.stringify(mode)}.`, planFile));

  if (CODE_ROLES.has(role)) {
    if (renderer !== "code" || placement !== "code") {
      findings.push(fail("placeholder-renderer-violation", `Element ${id} is ${role} and must be rendered as code, not ${renderer}/${placement}.`, planFile));
    }
    if (asset.generationScope && asset.generationScope !== "none") {
      findings.push(fail("full-ui-image2-generation", `Element ${id} is ${role}; simple UI/graphic primitives must not be generated by image2.`, planFile));
    }
  }

  if (RASTER_ROLES.has(role)) {
    if (!["image2", "project"].includes(renderer)) {
      findings.push(fail("asset-role-renderer-mismatch", `Element ${id} is semantic raster role ${role} and must use renderer=image2 or project.`, planFile));
    }
    if (renderer === "image2" && asset.generationScope !== "asset-only") {
      findings.push(fail("full-ui-image2-generation", `Element ${id} uses image2 but generationScope must be asset-only. Generate one clean visual asset, never a full UI screenshot to crop later.`, planFile));
    }
    if (asset.containsCodeOwnedText === true) {
      findings.push(fail("bitmap-code-content", `Element ${id} declares code-owned text/UI inside a semantic bitmap. Text and controls must be code-rendered.`, planFile));
    }
  }

  if (role === "cutout-subject") {
    if (placement !== "layered") findings.push(fail("asset-role-renderer-mismatch", `Cutout ${id} must use placement=layered.`, planFile));
    if (asset.requiresTransparency !== true) findings.push(fail("cutout-transparency-required", `Cutout ${id} must require transparency/background removal.`, planFile));
    if (asset.participatesInOverlap === true && mode !== "cutout-layered") {
      findings.push(fail("cutout-overlay-required", `Cutout ${id} participates in freeform overlap and must use overlayRole.mode=cutout-layered.`, planFile));
    }
  }

  if (mode === "cutout-layered" && role !== "cutout-subject") {
    findings.push(fail("asset-role-overlay-mismatch", `Element ${id} uses cutout-layered overlay but assetRole.role is ${role}; reclassify as cutout-subject or change overlay mode.`, planFile));
  }
  if (role === "background-plate" && placement !== "background") {
    findings.push(fail("asset-role-renderer-mismatch", `Background plate ${id} must use placement=background.`, planFile));
  }
  if (role === "background-plate" && mode === "cutout-layered") {
    findings.push(fail("asset-role-overlay-mismatch", `Background plate ${id} cannot use cutout-layered overlay.`, planFile));
  }
  if (role === "inline-photo" && placement !== "container") {
    findings.push(fail("asset-role-renderer-mismatch", `Inline photo ${id} must stay container-bound with placement=container.`, planFile));
  }
  if (role === "inline-photo" && mode === "cutout-layered") {
    findings.push(fail("asset-role-overlay-mismatch", `Inline photo ${id} cannot use freeform cutout-layered overlay; reclassify it as cutout-subject if the silhouette leaves its container.`, planFile));
  }

  const overlapMode = !["none", "side-by-side"].includes(mode);
  if (overlapMode && !["text-over-image", "image-over-text"].includes(overlay.zOrder)) {
    findings.push(fail("overlay-z-order-required", `Element ${id} overlaps text/image but has no explicit zOrder.`, planFile));
  }
  if (mode === "safe-overlap" && (!Array.isArray(overlay.textSafeZones) || overlay.textSafeZones.length === 0)) {
    findings.push(fail("overlay-safe-zone-required", `Element ${id} uses safe-overlap but declares no textSafeZones.`, planFile));
  }
  if (mode === "masked-overlay" && (!MASKS.has(overlay.mask) || overlay.mask === "none")) {
    findings.push(fail("overlay-mask-required", `Element ${id} uses masked-overlay but has no readability mask.`, planFile));
  }
  if (mode === "cutout-layered" && (!Array.isArray(overlay.subjectCriticalZones) || overlay.subjectCriticalZones.length === 0)) {
    findings.push(fail("subject-critical-zone-required", `Element ${id} uses cutout-layered but declares no subjectCriticalZones.`, planFile));
  }
  if (overlay.allowTextOverSubject === true && !nonEmpty(overlay.referenceBackedOverlapReason)) {
    findings.push(fail("subject-critical-overlap", `Element ${id} allows text over the subject but has no reference-backed reason.`, planFile));
  }
  if (overlay.safeArea && !["inside", "not-applicable"].includes(overlay.safeArea)) {
    findings.push(fail("safe-area-overlap", `Element ${id} has invalid safeArea contract ${JSON.stringify(overlay.safeArea)}.`, planFile));
  }
}

function findVisualRolePlan(rootDir) {
  return findNamedPlan(rootDir, "visual-role-plan.json");
}

function findNamedPlan(rootDir, name) {
  const direct = [path.join(rootDir, name), path.join(rootDir, "artifacts", name)].filter((file) => fs.existsSync(file));
  const runRoot = path.join(rootDir, ".image2-ui", "runs");
  const runtime = fs.existsSync(runRoot) ? findNamedFiles(runRoot, name) : [];
  const candidates = [...direct, ...runtime];
  candidates.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
  return candidates[0] || null;
}

function findNamedFiles(root, name) {
  const out = [];
  const stack = [root];
  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === name) out.push(full);
    }
  }
  return out;
}

function nonEmpty(value) {
  return typeof value === "string" && value.trim().length > 0;
}

function fail(rule, message, file) {
  return { level: "fail", rule, message, file };
}
